package ru.art.generator.soap.model;

public enum RestrictionOperation {
    ENUMERATION, MIN_EXCLUSIVE, MAX_EXCLUSIVE, PATTERN, WHITESPACE, LENGTH,
    MIN_LENGTH, MAX_LENGTH, FRACTION_DIGITS, TOTAL_DIGITS, MIN_INCLUSIVE,
    MAX_INCLUSIVE
}