package ru.art.service.constants;

public interface ServiceErrorCodes {
    String INTERNAL_ERROR = "SERVICE_INTERNAL_ERROR";
    String CHILD_SERVICE_ERROR = "CHILD_SERVICE_ERROR";
    String UNDECLARED_INTERNAL_ERROR = "SERVICE_UNDECLARED_INTERNAL_ERROR";
    String UNCAUGHT_INTERNAL_ERROR = "SERVICE_UNCAUGHT_INTERNAL_ERROR";
    String NPE = "SERVICE_NULL_POINTER_EXCEPTION";
    String UNKNOWN_METHOD_ERROR = "SERVICE_UNKNOWN_METHOD_ERROR";
}
