/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main
 * Method:    initializeReindexer
 * Signature: ()LReindexerError;
 */
JNIEXPORT jobject JNICALL Java_Main_initializeReindexer
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
