adk {
    embeddedModules {
        applicationCore()
        applicationEntity()
        applicationLogging()
        applicationService()
        applicationConfig()
        applicationConfigYaml()
        applicationProtobuf()
        applicationProtobufGenerated()
        applicationGrpc()
        applicationGrpcClient()
        applicationGrpcServer()
        applicationJson()
        applicationHttp()
        applicationHttpClient()
        applicationMetrics()
        applicationMetricsHttp()
        applicationHttpJson()
        applicationHttpServer()
        applicationRocksDb()
        applicationConfiguratorApi()
        applicationConfigRemoteApi()
    }
}