name: ART Java Pull Request
on: [ pull_request ]
jobs:
  gradle-build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-11, windows-latest ]
        jdk: [ 1.8, 11, 17 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build --max-workers 8 --configure-on-demand --parallel
